### PR TITLE
Two updates for tone platform.

### PR DESCRIPTION
**Pull request by sjllls**
The two commits had been tested.
1. The system lag caused by these thermal configs, we need disable them. I don't meet overheat problem after disabling them(Though msm8996 is hot), Maybe we could add msm simple thermal for it.

2.The EM you imported from EAS-Project is not suit for MSM8996 devices of SODP. I build two kernels and run Geekbench4. After importing EAS configs from Pixel, the scores increased a lot.
Show you screenshot.

3. I find another problem, there is a delay when CPU increases its frequency from a low status, about 0.2s, this make system a little lag.

Before importing EAS configs from Pixel
Screenshot_20190717-103332_Geekbench_4

After importing EAS configs from Pixel,
Screenshot_20190717-105122_Geekbench_4

### CODE REVIEW

**Comment by lazerl0rd** [comment]
Interesting, thanks. I’ll look into this.

**Comment by lazerl0rd** [comment]
So, in ZfSODP we use schedtune boosts. If it’s a bit laggy for you that’s kinda “good” for us as it means default battery usage is going to improve.

**Comment by lazerl0rd** [comment]
@sjllls I'm planning to remeasure all our EMs soon anyways per platform.

**Comment by sjllls** [comment]
> @sjllls I'm planning to remeasure all our EMs soon anyways per platform.

Yes, the EM of msm8996 is wrong. It's not suit for tone platform.
BTW, I thinks zfSODP could based on a custom rom like Los, RR, AOSPA, etc. Then, we will get much more functions than AOSP.

**Comment by lazerl0rd** [comment]
@sjllls I prefer to not be based on any custom ROM and implement features into the ROM manually. It gives it more fo a stock feel, to me.

And about the EM, I'm just waiting on a fellow dev to finish off a script I'll be using.

**Comment by sjllls** [comment]
> @sjllls I prefer to not be based on any custom ROM and implement features into the ROM manually. It gives it more fo a stock feel, to me.
> 
> And about the EM, I'm just waiting on a fellow dev to finish off a script I'll be using.

Ok, nice work!

**Pull request closed without merging**
